# Generated by Django 4.2.4 on 2023-09-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadebanho',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=90, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='reservadebanho',
            name='tamanho',
            field=models.CharField(default='0', max_length=10, verbose_name='Tamanho'),
        ),
        migrations.AddField(
            model_name='reservadebanho',
            name='turno',
            field=models.CharField(default='Manhã', max_length=45, verbose_name='Turno'),
        ),
    ]
